"""empty message

Revision ID: 73d50eb2ceee
Revises: 
Create Date: 2018-05-12 15:07:28.613088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d50eb2ceee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=64), nullable=True),
    sa.Column('center_location', sa.String(length=100), nullable=True),
    sa.Column('center_capacity', sa.Integer(), nullable=True),
    sa.Column('center_status', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_center_capacity'), 'center', ['center_capacity'], unique=False)
    op.create_index(op.f('ix_center_center_location'), 'center', ['center_location'], unique=False)
    op.create_index(op.f('ix_center_center_name'), 'center', ['center_name'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_event_name'), 'event', ['event_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['center.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_event_event_name'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_center_center_name'), table_name='center')
    op.drop_index(op.f('ix_center_center_location'), table_name='center')
    op.drop_index(op.f('ix_center_center_capacity'), table_name='center')
    op.drop_table('center')
    # ### end Alembic commands ###
